### ISSUE TITLE
WatchTower does not log all interactions

### ISSUE THREAD

**Issue by Greg-J** [LambdaCraft/watchtower#7]
We have tested this exhaustively and have yet to find out why or when it fails, but it fails a lot.

We can watch someone interact with a container and then use the `/wt tool` on it only to find that `/wt tool` reports the interaction incorrectly or fails to report interactions entirely. Someone will take a book and add two diamonds and it'll say they took two diamonds and added air. It's completely unreliable.

**Comment by unsupervisednn** [comment]
@Greg-J do you have some reproducible instructions to make this bug appear every time?

**Comment by unsupervisednn** [comment]
@Greg-J I've released a bug fix in 0.1.7

**Comment by Greg-J** [comment]
Has 0.1.7 been released?
